version: '2'

services:
        
  fdccaixa:
    build:
      context: .
      dockerfile: CaixaDockerfile
    image: willrapha/fdccaixa
    container_name: fdccaixa
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 0.5GB
    restart: unless-stopped
    networks:
      - fdc_vnet
    depends_on:
        - fdcmssql
      
  fdcrelatorio:
    build:
      context: .
      dockerfile: RelatorioDockerfile
    image: willrapha/fdcrelatorio
    container_name: fdcrelatorio
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 0.5GB
    networks:
      - fdc_vnet
    restart: unless-stopped
    depends_on:
        - fdcmssql

  fdcseguranca:
    build:
      context: .
      dockerfile: SegurancaDockerfile
    image: willrapha/fdcseguranca
    container_name: fdcseguranca
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 0.5GB
    networks:
      - fdc_vnet
    restart: unless-stopped
    depends_on:
        - fdcmssql
        
  fdccaixaservice:
    build:
      context: .
      dockerfile: CaixaServiceDockerfile
    image: willrapha/fdccaixaservice
    container_name: fdccaixaservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 0.5GB
    networks:
      - fdc_vnet
    restart: unless-stopped
    depends_on:
        - fdcrabbitmq
        
  nginx:
    build:
      context: ./nginx 
      dockerfile: Dockerfile
    image: willrapha/nginx
    container_name: fdcnginx
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 0.5GB
    networks:
      - fdc_vnet
    ports:
      - "80:80"
    depends_on:
        - fdcseguranca
        - fdcrelatorio
        - fdccaixa
    restart: unless-stopped
      
  fdcmssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: fdcsqlserver
    ports:
      - 6005:1433
    volumes:
      - ./sql/backup:/var/lib/mssqlql/data
      - ./sql/data:/var/opt/mssql/data
      - ./sql/secrets:/var/opt/mssql/secrets
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P455w0rd
    restart: unless-stopped
    networks:
      - fdc_vnet

  fdcrabbitmq:
    image: rabbitmq:3.6
    container_name: fdcrabbitmq
    environment:
      - "RABBITMQ_DEFAULT_PASS=8eVfq8DuUNX4"
      - "RABBITMQ_DEFAULT_USER=user"
    ports:
      - '5672:5672'
      - '15672:15672'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 0.5GB
    restart: unless-stopped
    networks:
            - fdc_vnet    
      
networks:
  fdc_vnet:
    name: fdc_vnet    
    external: true

